### ISSUE TITLE
"This is not a config file"

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#112]
### Expected behavior

To see the results table

### Actual Behavior

Popup with the message "This is not a config file"

![selection_130](https://user-images.githubusercontent.com/12729291/33838961-34e767a0-de91-11e7-97d9-73143c593660.png)

### Steps to reproduce the problem

1. Select data: Action potential dependent sIPSCs from a 3-4 months old C57BL/6J X SJL female mice hippocampus CA1 pyramidal cell (B5)
2. Use default mod file
3. Choose NSG 
4. Select all_traces
5. Run the simulation and wait until finished
6. Select 'storage'
7. Select exp-file: expB5.txt and config-file: configB5.txt (see screenshot)
8. Click on 'Results table'

### Optional infrastructural data (user, platform, browser, environment, ...)

Linux, Chrome, Test-A2-1

**Comment by clupascu** [comment]
I fixed this. Can you please test again? Thanks.

**Comment by alex4200** [comment]
I still get the same error. I start the first notebook and switch to the 'analysis' notebook when the NSG status is 'COMPLETED'. I choose the files as in the example above. 

Collab Test-A2-4

**Comment by clupascu** [comment]
It should be fixed now. Can you try again please? Thanks.

**Comment by alex4200** [comment]
Yes its fixed, thanks
