### ISSUE TITLE
Unable to select other computer than NSG

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#200]
### Expected behavior

Able to select JURECA (and MARCONI) for running the optimization.  Maybe not MARCONI for SGA1, but JURECA? 

### Actual Behavior

Unable to select either of these. Only NSG possible

- [x] Selection of PizDaint implemented for Hippocampus Circuit Building Optimization use cases
- [ ] Implementation pending for HH use case

**Comment by lbologna** [comment]
At the moment I removed the MARCONI and JURECA check-boxes.
I will leave this issue in this milestone for the next two weeks and eventually move it, if its implementation is postponed.
Being the NSG job submission working this issue is rather a "Type_Feature" than a "Type_BUG".
I changed the label accordingly.

**Comment by mmigliore** [comment]
Yes.

**Comment by alex4200** [comment]
Should be ready for the HBP summit in October.

**Comment by alex4200** [comment]
JURECA booster partitions are down whole November.

**Comment by clupascu** [comment]
Testing on PizDaint is performed. I hope that during code jam we can test optimizations launched through unicore on PizDaint.

**Comment by clupascu** [comment]
You have to write to hpac-support@humanbrainproject.eu and ask for an account on PizDaint to use HBP ICEI resources for SP6.

**Comment by alex4200** [comment]
According to @lbologna this ticket should be done by end of Jan 2019.

**Comment by alex4200** [comment]
@clupascu I took a look at the use cases:

1. For "Rebuild Single HippoCell" I was able to start the simulation on PizDaint. However, I did not find a way to check on the job in the "Job Manager". I see NSG only. (But the job seems to have completed successful on PizDaint).
2. In the "BuildOwn Single HippoCell" use case I encountered an error when clicking on "Create Piz Daint zip file":

![screen shot 2019-01-09 at 07 33 08](https://user-images.githubusercontent.com/12729291/50881447-e3af5a00-13e1-11e9-9f4d-e17a32fb40ba.png)

**Comment by clupascu** [comment]
@alex4200 For both usecases the check can be done only from the "Config" notebook. Once the job is submitted you can check the status of the job and once the job is successfull the results are moved to the storage. I will still have to modify the manager. 

I fixed the "BuildOwn Single HippoCell". Please test again. Thanks.

**Comment by alex4200** [comment]
@clupascu  In the use case "BuildOwn Single HippoCell" I get the following error:

![screen shot 2019-01-09 at 16 57 15](https://user-images.githubusercontent.com/12729291/50911214-b12c4e00-142f-11e9-882f-19b2ea9c83cc.png)

It looks like the definition for the function `get_oidc_auth` is missing (which is defined for the other use case).

**Comment by clupascu** [comment]
@alex4200 it should be fixed now. Can you please test again? Thanks.

**Comment by alex4200** [comment]
@clupascu  Yes that error is fixed now. Thanks

**Comment by alex4200** [comment]
There is still an issue for the HH usecase; @lbologna  will take a look after finishing #333

**Comment by lbologna** [comment]
Submission to pizdaint being finalized on the dev platform:
https://collab.humanbrainproject.eu/#/collab/1256/nav/29703
- Submission file (e.g. .zip) creation done.
- Job submission/fetching to be completed.

Ready to be tested by the end of the week

**Comment by lbologna** [comment]
Current status for job submission to pizdaint in hhnb:
- [x] frontend update with option for submission to pizdaint
- [x] submission file creation for pizdaint
- [x] job submission to pizdaint
- [x] pizdaint job list fetching
- [x] pizdaint single job results download
- [x] model upload to BlueNaaS 
- [x] model simulation on BlueNaaS

**Comment by lbologna** [comment]
@alex4200 job submission to Pizdaint in HHNB is available at the following test link:
https://collab.humanbrainproject.eu/#/collab/1256/nav/29703

Could you please start the testing?
Thank you!

**Comment by alex4200** [comment]
@lbologna The submission to PizDaint seems to work fine. NSG as well. From my side this can be put on PROD.

**Comment by lbologna** [comment]
Moved to production
