### ISSUE TITLE
"Save Analysis" in the Build own/Rebuild use cases  might not do anything

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#219]
### Expected behavior

When clicking on the button, I expect the generated pdf's to be stored in the storage

### Actual Behavior

The storage is still empty

### Steps to reproduce the problem

- Run the Config notebook, choose first model, do not change anything
- Wait until computation is done
- Open the analysis notebook, select 'storage', click on "View Analysis' and then on 'Save Analysis'
- Check the storage

**Comment by clupascu** [comment]
This should be fixed. Can you test again please? Thanks.

**Comment by alex4200** [comment]
@clupascu : It still does not work. I have tested this on the DEV environment.

Where would I find the pdf files exactly?

**Comment by clupascu** [comment]
Can you add me to the collab team?

**Comment by clupascu** [comment]
I fixed this. Can you please test again? Thanks.

**Comment by alex4200** [comment]
Works for both use cases on DEV. Thanks!
