### ISSUE TITLE
StorageArgumentException for SynapticEvents Fitting

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#232]
When doing the analysis on JURECA, a bug in `hbp_service_client` raises a StorageArgumentException.
The call
`clients.storage.mkdir(storeto)`

must become 
`clients.storage.mkdir(str(storeto))`

(and all other path calls to  `hbp_service_client`.

**Comment by clupascu** [comment]
This should be fixed. Can you test again please? Thanks.

**Comment by alex4200** [comment]
@clupascu : I am still getting the same error (Synaptic events fitting with user data):
```

StorageArgumentExceptionTraceback (most recent call last)
<ipython-input-11-adc4aeafd74b> in checksimunicore(CheckSU)
    201                 with open(f,"w") as local_file:
    202                     local_file.write(content)
--> 203                 clients.storage.upload_file(f,os.path.join(storeto,f),filetype)
    204         STU.layout.display='none'
    205         IU.layout.display='none'

/opt/conda/envs/python2/lib/python2.7/site-packages/hbp_service_client/storage_service/client.pyc in upload_file(self, local_file, dest_path, mimetype)
    208         '''
    209 
--> 210         self.__validate_storage_path(dest_path)
    211         # get the paths of the target dir and the target file name
    212         if dest_path.endswith('/'):

/opt/conda/envs/python2/lib/python2.7/site-packages/hbp_service_client/storage_service/client.pyc in __validate_storage_path(cls, path, projects_allowed)
    265         if not path or not isinstance(path, str) or path[0] != '/' or path == '/':
    266             raise StorageArgumentException(
--> 267                 'The path must be a string, start with a slash (/), and be longer'
    268                 ' than 1 character.')
    269         if not projects_allowed and len([elem for elem in path.split('/') if elem]) == 1:

StorageArgumentException: The path must be a string, start with a slash (/), and be longer than 1 character.
```

**Comment by clupascu** [comment]
This should be fixed now. Can you please test again? Thanks.

**Comment by alex4200** [comment]
Yes, fixed!
