### ISSUE TITLE
Server error displaying pdfs

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#71]
### Expected behavior

3 pdf files are being displayed

### Actual Behavior

500 Server error

### Steps to reproduce the problem

Follow the use case with the first model

Issue is related to #32.

**Comment by clupascu** [comment]
I fixed this. Can you please test again? Thanks.

**Comment by alex4200** [comment]
I still get a server error. Tested today 13:50 on notebook Test-C1-3, created new at 8:50 today. I added you

**Comment by clupascu** [comment]
Now it should be fixed. Can you test again please? Thanks.

**Comment by alex4200** [comment]
The pdf's are now displayed correctly.
